# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app
# copy package files
COPY package.json package-lock.json ./
# install dependencies without running setup scripts
RUN npm install --ignore-scripts
# copy source code
COPY . .
# create entrypoint.js to write config.json from MCP_CONFIG env var and run server
RUN printf "import fs from 'fs';\nimport { fileURLToPath } from 'url';\nimport { dirname } from 'path';\nconst __filename = fileURLToPath(import.meta.url);\nconst __dirname = dirname(__filename);\nconst raw = process.env.MCP_CONFIG;\nif(!raw){console.error('MCP_CONFIG env var missing');process.exit(1);}\nlet cfg;\ntry{cfg = JSON.parse(raw);}catch(e){console.error('Failed to parse MCP_CONFIG:', e.message);process.exit(1);}\nfs.writeFileSync(__dirname + '/config.json', JSON.stringify(cfg, null,2));\nimport('./index.js');" > entrypoint.js
# default command
CMD ["node", "entrypoint.js"]
